name: Playwright E2E (Docker Compose - tests only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Secrets feed directly into the tests container
    env:
      BASE_URL: ${{ secrets.BASE_URL }}         
      USER_EMAIL: ${{ secrets.USER_EMAIL }}      
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}# e.g. improvement

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Playwright tests in Docker
        run: docker compose up --exit-code-from tests tests

      # Artifacts
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
          retention-days: 30

      - name: Upload Playwright videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: test-results/**/video.webm
          retention-days: 14

      - name: Upload Playwright screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screens
          path: test-results/**/*.png
          retention-days: 14
