name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ✅ Preflight check before running tests
      - name: "Preflight: check BASE_URL reachability"
  env:
    BASE_URL: ${{ secrets.BASE_URL }}
  run: |
    if [ -z "$BASE_URL" ]; then 
      echo "❌ BASE_URL empty"; 
      exit 1; 
    fi
    echo "Checking $BASE_URL ..."
    curl -kL --max-time 10 -I "$BASE_URL" || (echo "❌ Unreachable from runner"; exit 1)


      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
