name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22           # match local/asdf (22.16.0)
          cache: 'npm'               # enable npm cache

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers + Linux deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests (headless on CI via config)
        env:
          BASE_URL: ${{ secrets.BASE_URL }}          # e.g. https://connect-staging.powerhrg.com
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: npx playwright test

      # Always keep the HTML report + traces
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
          retention-days: 30
